//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerLabRoom.WS_PTN {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_PTN.WS_PhongThiNghiemSoap")]
    public interface WS_PhongThiNghiemSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getListThietBi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getListThietBi(string mChungLoai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getListThietBi", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getListThietBiAsync(string mChungLoai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getThietBiToiHan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getThietBiToiHan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getThietBiToiHan", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getThietBiToiHanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getThietBiQuaHan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getThietBiQuaHan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getThietBiQuaHan", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getThietBiQuaHanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getListBaiThiNghiem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getListBaiThiNghiem(int MaGV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getListBaiThiNghiem", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getListBaiThiNghiemAsync(int MaGV);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_PhongThiNghiemSoapChannel : ManagerLabRoom.WS_PTN.WS_PhongThiNghiemSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_PhongThiNghiemSoapClient : System.ServiceModel.ClientBase<ManagerLabRoom.WS_PTN.WS_PhongThiNghiemSoap>, ManagerLabRoom.WS_PTN.WS_PhongThiNghiemSoap {
        
        public WS_PhongThiNghiemSoapClient() {
        }
        
        public WS_PhongThiNghiemSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_PhongThiNghiemSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_PhongThiNghiemSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_PhongThiNghiemSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getListThietBi(string mChungLoai) {
            return base.Channel.getListThietBi(mChungLoai);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getListThietBiAsync(string mChungLoai) {
            return base.Channel.getListThietBiAsync(mChungLoai);
        }
        
        public System.Data.DataSet getThietBiToiHan() {
            return base.Channel.getThietBiToiHan();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getThietBiToiHanAsync() {
            return base.Channel.getThietBiToiHanAsync();
        }
        
        public System.Data.DataSet getThietBiQuaHan() {
            return base.Channel.getThietBiQuaHan();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getThietBiQuaHanAsync() {
            return base.Channel.getThietBiQuaHanAsync();
        }
        
        public System.Data.DataSet getListBaiThiNghiem(int MaGV) {
            return base.Channel.getListBaiThiNghiem(MaGV);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getListBaiThiNghiemAsync(int MaGV) {
            return base.Channel.getListBaiThiNghiemAsync(MaGV);
        }
    }
}
